services:
  jobsearchapp.api:
    image: jobsearchapp.api
    build:
      context: .
      dockerfile: JobSearchApp.Api/Dockerfile
    ports:
      - "5000:8080"
  
  jobsearchapp.db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: JobSearchAppDb
    ports:
        - "5432:5432"
    volumes:
      - jobsearchapp-db:/var/lib/postgresql/data

volumes:
    jobsearchapp-db: